package com.example.demo.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class AccountDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_detail.order_num
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_detail.order_type
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_detail.create_time
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_detail.order_account
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private BigDecimal orderAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_detail.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_detail.order_num
     *
     * @return the value of account_detail.order_num
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_detail.order_num
     *
     * @param orderNum the value for account_detail.order_num
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_detail.order_type
     *
     * @return the value of account_detail.order_type
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_detail.order_type
     *
     * @param orderType the value for account_detail.order_type
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_detail.create_time
     *
     * @return the value of account_detail.create_time
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_detail.create_time
     *
     * @param createTime the value for account_detail.create_time
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_detail.order_account
     *
     * @return the value of account_detail.order_account
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public BigDecimal getOrderAccount() {
        return orderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_detail.order_account
     *
     * @param orderAccount the value for account_detail.order_account
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setOrderAccount(BigDecimal orderAccount) {
        this.orderAccount = orderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_detail.user_name
     *
     * @return the value of account_detail.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_detail.user_name
     *
     * @param userName the value for account_detail.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}