package com.example.demo.pojo;

public class BankInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_info.user_id
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_info.bank_card
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private String bankCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_info.bank_activation
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private String bankActivation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_info.sub_bank
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private String subBank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_info.bank_name
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private String bankName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_info.user_id
	 * @return  the value of bank_info.user_id
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_info.user_id
	 * @param userId  the value for bank_info.user_id
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_info.bank_card
	 * @return  the value of bank_info.bank_card
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public String getBankCard() {
		return bankCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_info.bank_card
	 * @param bankCard  the value for bank_info.bank_card
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setBankCard(String bankCard) {
		this.bankCard = bankCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_info.bank_activation
	 * @return  the value of bank_info.bank_activation
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public String getBankActivation() {
		return bankActivation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_info.bank_activation
	 * @param bankActivation  the value for bank_info.bank_activation
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setBankActivation(String bankActivation) {
		this.bankActivation = bankActivation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_info.sub_bank
	 * @return  the value of bank_info.sub_bank
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public String getSubBank() {
		return subBank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_info.sub_bank
	 * @param subBank  the value for bank_info.sub_bank
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setSubBank(String subBank) {
		this.subBank = subBank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_info.bank_name
	 * @return  the value of bank_info.bank_name
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_info.bank_name
	 * @param bankName  the value for bank_info.bank_name
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
}