package com.example.demo.pojo;

public class GameInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_info.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_info.game_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String gameName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_info.user_name
     *
     * @return the value of game_info.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_info.user_name
     *
     * @param userName the value for game_info.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_info.game_name
     *
     * @return the value of game_info.game_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_info.game_name
     *
     * @param gameName the value for game_info.game_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }
}