package com.example.demo.pojo;

public class SysAdmin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_admin.sys_id
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private Integer sysId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_admin.sys_name
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private String sysName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_admin.sys_phone
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private String sysPhone;
	
	private String sysPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_admin.sys_mail
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private String sysMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_admin.sys_status
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	private String sysStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_admin.sys_id
	 * @return  the value of sys_admin.sys_id
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public Integer getSysId() {
		return sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_admin.sys_id
	 * @param sysId  the value for sys_admin.sys_id
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setSysId(Integer sysId) {
		this.sysId = sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_admin.sys_name
	 * @return  the value of sys_admin.sys_name
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public String getSysName() {
		return sysName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_admin.sys_name
	 * @param sysName  the value for sys_admin.sys_name
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_admin.sys_phone
	 * @return  the value of sys_admin.sys_phone
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public String getSysPhone() {
		return sysPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_admin.sys_phone
	 * @param sysPhone  the value for sys_admin.sys_phone
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setSysPhone(String sysPhone) {
		this.sysPhone = sysPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_admin.sys_mail
	 * @return  the value of sys_admin.sys_mail
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public String getSysMail() {
		return sysMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_admin.sys_mail
	 * @param sysMail  the value for sys_admin.sys_mail
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setSysMail(String sysMail) {
		this.sysMail = sysMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_admin.sys_status
	 * @return  the value of sys_admin.sys_status
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public String getSysStatus() {
		return sysStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_admin.sys_status
	 * @param sysStatus  the value for sys_admin.sys_status
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	public void setSysStatus(String sysStatus) {
		this.sysStatus = sysStatus;
	}

	public String getSysPwd() {
		return sysPwd;
	}

	public void setSysPwd(String sysPwd) {
		this.sysPwd = sysPwd;
	}
}