package com.example.demo.pojo;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sys_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private Integer sysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_phone
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_mail
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String userMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.enter_pw
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String enterPw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.drawing_account_pw
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String drawingAccountPw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.group_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_status
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    private String userStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sys_id
     *
     * @return the value of user_info.sys_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public Integer getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sys_id
     *
     * @param sysId the value for user_info.sys_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setSysId(Integer sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_phone
     *
     * @return the value of user_info.user_phone
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_phone
     *
     * @param userPhone the value for user_info.user_phone
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_mail
     *
     * @return the value of user_info.user_mail
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_mail
     *
     * @param userMail the value for user_info.user_mail
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.enter_pw
     *
     * @return the value of user_info.enter_pw
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getEnterPw() {
        return enterPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.enter_pw
     *
     * @param enterPw the value for user_info.enter_pw
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setEnterPw(String enterPw) {
        this.enterPw = enterPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.drawing_account_pw
     *
     * @return the value of user_info.drawing_account_pw
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getDrawingAccountPw() {
        return drawingAccountPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.drawing_account_pw
     *
     * @param drawingAccountPw the value for user_info.drawing_account_pw
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setDrawingAccountPw(String drawingAccountPw) {
        this.drawingAccountPw = drawingAccountPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.group_id
     *
     * @return the value of user_info.group_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.group_id
     *
     * @param groupId the value for user_info.group_id
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_status
     *
     * @return the value of user_info.user_status
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_status
     *
     * @param userStatus the value for user_info.user_status
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }
}