package com.example.demo.dao;

import com.example.demo.pojo.AccountDetail;

public interface AccountDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_detail
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    int insert(AccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_detail
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    int insertSelective(AccountDetail record);
}