package com.example.demo.dao;

import com.example.demo.pojo.BankInfo;

public interface BankInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_info
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	int insert(BankInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_info
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	int insertSelective(BankInfo record);
}