package com.example.demo.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.example.demo.pojo.BankInfo;

@Repository
public interface BankInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_info
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	Integer insert(BankInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_info
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	Integer insertSelective(BankInfo record);
	
	
	List<BankInfo> selectByUserId(Integer userId);
	
	Integer deleteByCardId(String bankCard);

	Integer countByBankCard(String bankCard);

	BankInfo selectBankInfo(Map<String, Object> map);
	
}