package com.example.demo.dao;

import com.example.demo.pojo.GameInfo;

public interface GameInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_info
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    int insert(GameInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_info
     *
     * @mbg.generated Tue Mar 19 15:39:42 CST 2019
     */
    int insertSelective(GameInfo record);
}