package com.example.demo.dao;

import com.example.demo.pojo.SysAdmin;

public interface SysAdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	Integer deleteByPrimaryKey(Integer sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	Integer insert(SysAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	Integer insertSelective(SysAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	SysAdmin selectByPrimaryKey(Integer sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	Integer updateByPrimaryKeySelective(SysAdmin record);

	/** 
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	Integer updateByPrimaryKey(SysAdmin record);
	
	Integer countByName(String sysName);
	
	SysAdmin selectBySysName(String sysName);
}