package com.example.demo.dao;

import com.example.demo.pojo.SysAdmin;

public interface SysAdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	int deleteByPrimaryKey(Integer sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	int insert(SysAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	int insertSelective(SysAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	SysAdmin selectByPrimaryKey(Integer sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	int updateByPrimaryKeySelective(SysAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_admin
	 * @mbg.generated  Tue Mar 19 15:39:42 CST 2019
	 */
	int updateByPrimaryKey(SysAdmin record);
}